version: "3"
services:
  app:
    image: week6_userservice
    build:
     context: ./week6-userservice
    ports:
      - "3001:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/microservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=morveotesi

  db:
    image: "postgres:14.4-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=morveotesi

  rabbitmq:
    image: "rabbitmq:3.10-management"
    ports:
      - "5672:5672"
      - "15672:15672"
